const fortunes: string[] = [
  "The best way to predict the future is to invent it. — Alan Kay",
  "Talk is cheap. Show me the code. — Linus Torvalds",
  "First, solve the problem. Then, write the code. — John Johnson",
  "The most disastrous thing that you can ever learn is your first programming language. — Alan Kay",
  "Simplicity is the soul of efficiency. — Austin Freeman",
  "Code is like humor. When you have to explain it, it's bad. — Cory House",
  "Fix the cause, not the symptom. — Steve Maguire",
  "Optimism is an occupational hazard of programming: feedback is the treatment. — Kent Beck",
  "Make it work, make it right, make it fast. — Kent Beck",
  "Before software can be reusable it first has to be usable. — Ralph Johnson",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. — Martin Fowler",
  "Programming is not about typing, it's about thinking. — Rich Hickey",
  "The function of good software is to make the complex appear to be simple. — Grady Booch",
  "Java is to JavaScript what car is to carpet. — Chris Heilmann",
  "Truth can only be found in one place: the code. — Robert C. Martin",
  "A good programmer is someone who always looks both ways before crossing a one-way street. — Doug Linder",
  "It's not a bug — it's an undocumented feature.",
  "There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors. — Phil Karlton",
  "Weeks of coding can save you hours of planning.",
  "The best error message is the one that never shows up. — Thomas Fuchs",
  "In order to be irreplaceable, one must always be different. — Coco Chanel",
  "The computer was born to solve problems that did not exist before. — Bill Gates",
  "Software is a great combination between artistry and engineering. — Bill Gates",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in. — Edsger Dijkstra",
  "The most important property of a program is whether it accomplishes the intention of its user. — C.A.R. Hoare",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. — Bill Gates",
  "Don't worry if it doesn't work right. If everything did, you'd be out of a job. — Mosher's Law",
  "It's OK to figure out murder mysteries, but you shouldn't need to figure out code. You should be able to read it. — Steve McConnell",
  "One man's constant is another man's variable. — Alan Perlis",
  "Beware of bugs in the above code; I have only proved it correct, not tried it. — Donald Knuth",
  "The only way to learn a new programming language is by writing programs in it. — Dennis Ritchie",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code. — Dan Salomon",
  "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away. — Antoine de Saint-Exupery",
  "Java: write once, debug everywhere.",
  "Deleted code is debugged code. — Jeff Sickel",
  "If you can't explain it simply, you don't understand it well enough. — Albert Einstein",
  "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
  "There is no Ctrl+Z in life.",
  "A SQL query walks into a bar, sees two tables and asks... 'Can I JOIN you?'",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "There are 10 types of people in this world: those who understand binary and those who don't.",
  "!false — it's funny because it's true.",
  "A child asked his father, 'Why do programmers always mix up Halloween and Christmas?' — 'Because Oct 31 = Dec 25.'",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning. — Rick Cook",
  "The cloud is just someone else's computer.",
  "To iterate is human, to recurse divine. — L. Peter Deutsch",
  "Git commit -m 'Fixed bug' — Nobody: ... Literally nobody was fooled.",
  "Your code is like your humor. If you have to explain it, it's not good.",
  "The only thing more dangerous than a programmer with a screwdriver is a programmer with a root password.",
  "You should name a variable using the same care with which you name a first-born child. — Robert C. Martin",
  "Computers are fast; programmers keep being slow.",
  "99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around... 127 little bugs in the code.",
];

export function getFortune(): string {
  return fortunes[Math.floor(Math.random() * fortunes.length)];
}

export function getAllFortunes(): string[] {
  return fortunes;
}
